theme: jekyll-theme-minimal
title: Merry ModJam 2020
description: Welcome to Merry ModJam, the Christmas Mod Jam for Fabric 1.16.4, a community event in order to bring out the best of the Fabric Modloader!
logo: /mmj2020logo.png
